baseURL = 'https://kelvinQC.github.io/'
locale = 'en'
title = 'Qichao Blog'
theme = 'hugo-theme-monochrome'

[params]
footer = "Copyright © 2026 by Qichao" # default: None
toc_position = "right"
enable_collapsible_toc = false # default: false
enable_collapsible_changelogs = false # default: false

[[menu.navbar]]
identifier = "about"
name = "about"
title = "about"
url = "/about/"
weight = 100

[[menu.navbar]]
identifier = "series"
name = "series"
url = "/series/"
weight = -100

[[menu.navbar]]
identifier = "categories"
name = "categories"
url = "/categories/"
weight = 80

